"""Job application agents integrations package."""

from .base import (
    BaseEmailClient,
    BaseEmailParser,
    BaseJobDestination,
    BaseJobScraper,
    IntegrationRegistry,
    JobSourceIntegration,
    registry,
)
from .config import IntegrationsConfig, default_config
from .email import (
    DirectATSPostingParser,
    EmailParserRegistry,
    GenericJobAlertParser,
    GlassdoorJobAlertParser,
    GmailClient,
    GmailApiClient,
    GmailApiConfigurationError,
    FallbackEmailClient,
    ProcessedEmailLedger,
    ProviderFilterResult,
    ProviderMatch,
    ProviderSettingsError,
    IndeedJobAlertParser,
    LinkedInJobAlertParser,
    parser_registry,
    create_email_client,
    filter_message,
    load_provider_settings,
    normalize_message_id,
    normalize_search_text,
    validate_provider_settings,
)
from .models import (
    EmailAccountConfig,
    EmailMessage,
    IngestedJob,
    IngestionResult,
    JobAlertItem,
    NormalizedJobPosting,
    ScrapedJobContent,
)
from .pipeline import (
    FileSystemStagingDestination,
    FirestoreQueueDestination,
    JobIngestionPipeline,
    NotionBoardDestination,
)
from .scrapers import (
    HttpJobScraper,
    HybridJobScraper,
    JobPostingExtractor,
    PlaywrightJobScraper,
    is_bot_blocked,
)

__version__ = "0.1.0"

__all__ = [
    "BaseEmailClient",
    "BaseEmailParser",
    "BaseJobDestination",
    "BaseJobScraper",
    "IntegrationRegistry",
    "JobSourceIntegration",
    "registry",
    "IntegrationsConfig",
    "default_config",
    "EmailAccountConfig",
    "EmailMessage",
    "JobAlertItem",
    "ScrapedJobContent",
    "NormalizedJobPosting",
    "IngestedJob",
    "IngestionResult",
    "GmailClient",
    "GmailApiClient",
    "GmailApiConfigurationError",
    "FallbackEmailClient",
    "create_email_client",
    "ProcessedEmailLedger",
    "ProviderFilterResult",
    "ProviderMatch",
    "ProviderSettingsError",
    "LinkedInJobAlertParser",
    "IndeedJobAlertParser",
    "GlassdoorJobAlertParser",
    "DirectATSPostingParser",
    "GenericJobAlertParser",
    "EmailParserRegistry",
    "parser_registry",
    "filter_message",
    "load_provider_settings",
    "normalize_message_id",
    "normalize_search_text",
    "validate_provider_settings",
    "HttpJobScraper",
    "PlaywrightJobScraper",
    "HybridJobScraper",
    "JobPostingExtractor",
    "is_bot_blocked",
    "JobIngestionPipeline",
    "FileSystemStagingDestination",
    "NotionBoardDestination",
    "FirestoreQueueDestination",
]
