steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/latex-worker', '-f', 'deploy/docker/latex-worker/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/latex-worker']

images:
  - 'gcr.io/$PROJECT_ID/latex-worker'

options:
  logging: CLOUD_LOGGING_ONLY
