from __future__ import annotations

from typing import Any, Protocol

from .models import ArtifactRef, RenderJob, RenderRequest


class RenderJobRepository(Protocol):
    def enqueue(self, request: RenderRequest, idempotency_key: str) -> RenderJob: ...
    def requeue_expired(self) -> int: ...
    def claim(self, worker_id: str, lease_seconds: int = 360) -> RenderJob | None: ...
    def heartbeat(self, job_id: str, worker_id: str, lease_seconds: int = 360) -> bool: ...
    def succeed(
        self, job_id: str, worker_id: str, output: ArtifactRef, result: dict[str, Any]
    ) -> None: ...
    def fail(
        self, job_id: str, worker_id: str, code: str, detail: str, retryable: bool
    ) -> None: ...
    def get(self, job_id: str) -> RenderJob: ...
    def register_worker(
        self, worker_id: str, image_version: str, capabilities: dict[str, Any]
    ) -> None: ...
    def worker_ready(self, maximum_age_seconds: int = 90) -> bool: ...
