#!/usr/bin/env python3
"""Guided, repeatable setup for the Job Application Agents plugin."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


PLUGIN_NAME = "job-application-agents"
MARKETPLACE_NAME = "personal"
REQUIRED_TOOLS = ("python3", "codex", "xelatex", "kpsewhich", "pdfinfo", "pdftotext")


def command_exists(name: str) -> bool:
    return shutil.which(name) is not None


def missing_latex_packages() -> list[str]:
    kpsewhich = shutil.which("kpsewhich")
    if not kpsewhich:
        return ["kpsewhich"]
    required = (
        "fontspec.sty", "geometry.sty", "xcolor.sty", "titlesec.sty",
        "fancyhdr.sty", "enumitem.sty", "graphicx.sty", "hyperref.sty", "tabularx.sty",
        "fontawesome5.sty", "mfirstuc.sty", "parskip.sty", "tikz.sty", "adjustbox.sty",
    )
    missing = []
    for package in required:
        result = subprocess.run([kpsewhich, package], text=True, capture_output=True, check=False)
        if result.returncode or not result.stdout.strip():
            missing.append(package)
    return missing


def dependency_commands() -> list[list[str]]:
    if command_exists("dnf"):
        return [["sudo", "dnf", "install", "-y", "texlive-xetex", "texlive-collection-fontsrecommended", "texlive-collection-latexextra", "poppler-utils"]]
    if command_exists("apt-get"):
        return [["sudo", "apt-get", "install", "-y", "texlive-xetex", "texlive-fonts-recommended", "texlive-latex-extra", "poppler-utils", "python3-venv"]]
    if command_exists("brew"):
        return [["brew", "install", "--cask", "mactex-no-gui"], ["brew", "install", "poppler"]]
    return []


def ask(prompt: str) -> bool:
    try:
        return input(f"{prompt} [y/N] ").strip().lower() in {"y", "yes"}
    except EOFError:
        return False


def run(command: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, text=True, check=check)


def copy_plugin(repo: Path, destination: Path) -> None:
    ignored = shutil.ignore_patterns(".git", ".agents", ".codex", ".venv", "__pycache__", "*.pyc", "applications", "sources", "master-curriculum")
    temporary = Path(tempfile.mkdtemp(prefix=f".{PLUGIN_NAME}-", dir=destination.parent))
    try:
        shutil.copytree(repo, temporary / PLUGIN_NAME, ignore=ignored)
        if destination.exists():
            stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
            backup = destination.with_name(destination.name + f".previous-{stamp}-{os.getpid()}")
            destination.replace(backup)
        (temporary / PLUGIN_NAME).replace(destination)
    finally:
        shutil.rmtree(temporary, ignore_errors=True)


def update_marketplace(home: Path) -> tuple[Path, str]:
    path = home / ".agents" / "plugins" / "marketplace.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict) or not isinstance(data.get("plugins", []), list):
            raise ValueError(f"invalid personal marketplace: {path}")
    else:
        data = {"name": MARKETPLACE_NAME, "interface": {"displayName": "Personal"}, "plugins": []}
    marketplace_name = data.get("name")
    if not isinstance(marketplace_name, str) or not marketplace_name:
        raise ValueError(f"personal marketplace has no valid name: {path}")
    entry = {
        "name": PLUGIN_NAME,
        "source": {"source": "local", "path": f"./.codex/plugins/{PLUGIN_NAME}"},
        "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
        "category": "Productivity",
    }
    data["plugins"] = [item for item in data["plugins"] if item.get("name") != PLUGIN_NAME] + [entry]
    temporary = path.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    temporary.replace(path)
    return path, marketplace_name


def first_party_scripts(plugin: Path) -> list[Path]:
    paths = list((plugin / "scripts").glob("*.py"))
    paths.extend(plugin.glob("skills/*/scripts/*.py"))
    return sorted(path.resolve() for path in paths if not path.name.startswith("test_"))


def write_rules(home: Path, plugins: list[Path]) -> Path:
    path = home / ".codex" / "rules" / f"{PLUGIN_NAME}.rules"
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by job-application-agents/scripts/setup.py."]
    scripts = sorted({script for plugin in plugins for script in first_party_scripts(plugin)})
    for script in scripts:
        lines.extend([
            "prefix_rule(",
            f"    pattern = [\"python3\", {json.dumps(str(script))}],",
            "    decision = \"allow\",",
            "    justification = \"Run a bundled job-application validator or renderer.\",",
            f"    match = [{json.dumps('python3 ' + str(script) + ' --help')}],",
            ")",
            "",
        ])
    temporary = path.with_suffix(".rules.tmp")
    temporary.write_text("\n".join(lines), encoding="utf-8")
    temporary.replace(path)
    return path


def readiness(repo: Path, data_root: Path) -> tuple[list[str], list[str]]:
    ready: list[str] = []
    blocked: list[str] = []
    for tool in REQUIRED_TOOLS:
        (ready if command_exists(tool) else blocked).append(f"tool: {tool}")
    for package in missing_latex_packages() if command_exists("kpsewhich") else []:
        blocked.append(f"latex package: {package}")
    if (repo / ".codex-plugin" / "plugin.json").is_file():
        ready.append("plugin manifest")
    else:
        blocked.append("plugin manifest")
    if data_root.is_dir():
        ready.append(f"data root: {data_root}")
    else:
        blocked.append(f"data root: {data_root}")
    return ready, blocked


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--check", action="store_true", help="diagnose without changing anything")
    result.add_argument("--data-root", type=Path, default=Path.home() / "Documents" / "job-search")
    result.add_argument("--skip-notion-login", action="store_true")
    return result


def main() -> int:
    args = parser().parse_args()
    repo = Path(__file__).resolve().parent.parent
    data_root = args.data_root.expanduser().resolve()
    print(f"Job Application Agents setup ({platform.system()})")
    if args.check:
        ready, blocked = readiness(repo, data_root)
        for item in ready:
            print(f"READY   {item}")
        for item in blocked:
            print(f"BLOCKED {item}")
        return 1 if blocked else 0

    missing = [name for name in REQUIRED_TOOLS if not command_exists(name)]
    system_missing = [name for name in missing if name not in {"python3", "codex"}]
    latex_missing = missing_latex_packages() if command_exists("kpsewhich") else []
    if system_missing or latex_missing:
        commands = dependency_commands()
        details = system_missing + [f"LaTeX {name}" for name in latex_missing]
        print("Missing rendering dependencies: " + ", ".join(details))
        if commands:
            print("Proposed package commands:")
            for command in commands:
                print("  " + " ".join(command))
            if ask("Run these package commands now?"):
                for command in commands:
                    run(command)
        else:
            print("No supported package manager was detected; install XeLaTeX and Poppler manually.")
    if not command_exists("codex"):
        print("BLOCKED Codex CLI is required before setup can continue.", file=sys.stderr)
        return 1

    for directory in ("sources", "applications", "master-curriculum", "applications/.workflow-runs"):
        (data_root / directory).mkdir(parents=True, exist_ok=True)
    home = Path.home()
    plugin = home / ".codex" / "plugins" / PLUGIN_NAME
    plugin.parent.mkdir(parents=True, exist_ok=True)
    copy_plugin(repo, plugin)
    marketplace, marketplace_name = update_marketplace(home)
    result = subprocess.run(["codex", "plugin", "add", f"{PLUGIN_NAME}@{marketplace_name}"], text=True)
    if result.returncode:
        print("Plugin registration needs attention; rerun setup after resolving the Codex message above.", file=sys.stderr)
    cache_roots = [path for path in (home / ".codex" / "plugins" / "cache").glob(f"*/{PLUGIN_NAME}/*") if path.is_dir()]
    rules = write_rules(home, [repo, plugin, *cache_roots])
    if not args.skip_notion_login and ask("Connect Notion now in your browser?"):
        subprocess.run(["codex", "mcp", "login", "notion"], text=True)

    print(f"READY   data root: {data_root}")
    print(f"READY   personal marketplace: {marketplace}")
    print(f"READY   scoped command rules: {rules}")
    print("NEXT    Restart Codex, then run: python3 scripts/launch.py")
    print("NEXT    Ask: Prepare this job application: <public job URL>")
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
